### ISSUE TITLE
error: SSL: CERTIFICATE_VERIFY_FAILED 

### ISSUE THREAD

**Issue by Rahul5214** [phanimahesh/iitd-pyproxylogin#2]
Let's take a moment to appreciate your work towards IITD community.  

_Environment:_ 

```
rahul@Inspiron:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.10
Release:	16.10
Codename:	yakkety
rahul@Inspiron:~$ uname -a
Linux Inspiron 4.8.0-22-generic #24-Ubuntu SMP Sat Oct 8 09:15:00 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

I'm getting `SSL` error while running the `login.py` script. Found a work around by adding this in script.
[source](http://stackoverflow.com/questions/27835619/ssl-certificate-verify-failed-error)
```

import ssl
ssl._create_default_https_context = ssl._create_unverified_context
```
Now script is working fine (tested several times) and I'am sure there's nicer and safer way of getting rid of this error.

Also around line 81, I have change this 
`htmlsoup=soup(html) `
to this
`htmlsoup=soup(html, "lxml")`
 to get rid of this

```
The code that caused this warning is on line 84 of the file login.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "lxml")

  markup_type=markup_type))
```

**Comment by phanimahesh** [comment]
Didn't expect this to be used by anyone. Good to know.

I'll edit it to make using lxml explicit, but your first change, making ssl accept any garbage, is, not a good idea, to put it mildly. Please add ca certificate of iitd to your system instead. Get it from cc.iitd.ac.in/CSC, aand verify the fingerprint.

Good to know there are other tinkerers on campus, but understand what you do instead of blindly following instructions. Allowing any unverified certs, as a fix for an error that reads `SSL_CERT_VERIFY_FAILED` should've triggered an alarm. Verifications are usually there for a reason.

I've suggested CSC to switch to LE backed certs but a few in there don't trust any external entities enough to do that. We have a mix of extra careful people and absolutely careless people on campus, with unfortunate results, this being one of them.

**Comment by Rahul5214** [comment]
Got the certificate and imported to the system. As of now I'am using it with
`nohup python3 login.py &`
 command to run the script in background. Yes I don't want to waste my terminal session and if I want to logout I can always use `fg`.
 
Also from this [page](https://www.quora.com/How-can-I-bypass-IIT-Delhi-proxy-to-make-it-work-like-normal-internet) I used your proxy and git configuration settings and wrote a little [bash script](https://github.com/Rahul5214/proxy_git_settings) for automatic proxy and git setting and many Ubuntu users on campus are using that script and again credits goes to you.
